#include <fmod/fmod.hpp>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>
static FILE* dest; static unsigned frames=0;
static void check(FMOD_RESULT r){if(r){fprintf(stderr,"FMOD error %d\n",r);exit(1);}}
static FMOD_RESULT F_CALLBACK capture(FMOD_DSP_STATE*, float* in,float* out,unsigned n,int channels,int* outchannels){memcpy(out,in,n*channels*sizeof(float));fwrite(in,sizeof(float),n*channels,dest);frames+=n;return FMOD_OK;}
int main(int argc,char** argv){if(argc<3){fprintf(stderr,"usage: native_limiter_probe release_ms output.f32 [ceiling_db gain_db linked]\n");return 2;}float release=atof(argv[1]);dest=fopen(argv[2],"wb");if(!dest){perror(argv[2]);return 2;}FMOD::System* s;check(FMOD::System_Create(&s));check(s->setOutput(FMOD_OUTPUTTYPE_NOSOUND_NRT));check(s->setSoftwareFormat(48000,FMOD_SPEAKERMODE_STEREO,0));check(s->setDSPBufferSize(512,4));check(s->init(32,FMOD_INIT_NORMAL,nullptr));std::vector<float> pcm(8192*2);for(unsigned i=0;i<8192;++i){pcm[i*2]=0.25f;pcm[i*2+1]=0.125f;if(i>=256&&i<384)pcm[i*2]=4.0f;if(i==1536)pcm[i*2]=-2.0f;if(i>=3072&&i<3328)pcm[i*2+1]=2.0f;}FMOD_CREATESOUNDEXINFO info{};info.cbsize=sizeof(info);info.length=pcm.size()*sizeof(float);info.numchannels=2;info.defaultfrequency=48000;info.format=FMOD_SOUND_FORMAT_PCMFLOAT;FMOD::Sound* sound;check(s->createSound((char*)pcm.data(),FMOD_OPENMEMORY|FMOD_OPENRAW,&info,&sound));FMOD::Channel* channel;check(s->playSound(sound,nullptr,true,&channel));FMOD::DSP* eq;check(s->createDSPByType(FMOD_DSP_TYPE_LIMITER,&eq));check(eq->setParameterFloat(0,release));if(argc>3)check(eq->setParameterFloat(1,atof(argv[3])));if(argc>4)check(eq->setParameterFloat(2,atof(argv[4])));if(argc>5)check(eq->setParameterBool(3,atoi(argv[5])!=0));check(channel->addDSP(0,eq));FMOD_DSP_DESCRIPTION desc{};desc.pluginsdkversion=FMOD_PLUGIN_SDK_VERSION;strcpy(desc.name,"Capture");desc.numinputbuffers=1;desc.numoutputbuffers=1;desc.read=capture;FMOD::DSP* tap;check(s->createDSP(&desc,&tap));check(channel->addDSP(0,tap));check(channel->setPaused(false));while(frames<8192)check(s->update());check(s->release());fclose(dest);printf("captured %u frames\n",frames);}
