#include <fmod/fmod.hpp>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>
static FILE* dest; static unsigned frames=0;
static void check(FMOD_RESULT r){if(r){fprintf(stderr,"FMOD error %d\n",r);exit(1);}}
static FMOD_RESULT F_CALLBACK capture(FMOD_DSP_STATE*, float* in,float* out,unsigned n,int channels,int* outchannels){memcpy(out,in,n*channels*sizeof(float));fwrite(in,sizeof(float),n*channels,dest);frames+=n;return FMOD_OK;}
int main(int argc,char** argv){if(argc<3){fprintf(stderr,"usage: native_compressor_probe unused output.f32 [buffer-frames] [attack-ms] [constant-amplitude] [right-amplitude] [group-volume] [dsp-index] [volume-ramp] [channel-target]\n");return 2;}float release=atof(argv[1]);dest=fopen(argv[2],"wb");if(!dest){perror(argv[2]);return 2;}FMOD::System* s;check(FMOD::System_Create(&s));check(s->setOutput(FMOD_OUTPUTTYPE_NOSOUND_NRT));check(s->setSoftwareFormat(48000,FMOD_SPEAKERMODE_STEREO,0));check(s->setDSPBufferSize(argc>3?atoi(argv[3]):512,4));check(s->init(32,FMOD_INIT_NORMAL,nullptr));std::vector<float> pcm(8192*2);for(unsigned i=0;i<8192;++i){pcm[i*2]=0.25f;pcm[i*2+1]=0.125f;if(i>=256&&i<384)pcm[i*2]=4.0f;if(i==1536)pcm[i*2]=-2.0f;if(i>=3072&&i<3328)pcm[i*2+1]=2.0f;}if(argc>5)for(float& sample:pcm)sample=atof(argv[5]);if(argc>6)for(unsigned i=0;i<8192;++i)pcm[i*2+1]=atof(argv[6]);FMOD_CREATESOUNDEXINFO info{};info.cbsize=sizeof(info);info.length=pcm.size()*sizeof(float);info.numchannels=2;info.defaultfrequency=48000;info.format=FMOD_SOUND_FORMAT_PCMFLOAT;FMOD::Sound* sound;check(s->createSound((char*)pcm.data(),FMOD_OPENMEMORY|FMOD_OPENRAW,&info,&sound));const bool channelTarget=argc>10&&atoi(argv[10]);FMOD::ChannelGroup* group=nullptr;if(argc>7&&!channelTarget){check(s->createChannelGroup("SFX",&group));check(group->setVolumeRamp(argc>9?atoi(argv[9])!=0:false));check(group->setVolume(atof(argv[7])));}FMOD::Channel* channel;check(s->playSound(sound,group,true,&channel));if(channelTarget){check(channel->setVolumeRamp(argc>9?atoi(argv[9])!=0:false));check(channel->setVolume(atof(argv[7])));}FMOD::DSP* eq;check(s->createDSPByType(FMOD_DSP_TYPE_COMPRESSOR,&eq));check(eq->setParameterFloat(0,-10));check(eq->setParameterFloat(1,3));check(eq->setParameterFloat(2,argc>4?atof(argv[4]):180));check(eq->setParameterFloat(3,250));check(eq->setParameterFloat(4,5));if(group){if(argc<=8||atoi(argv[8])>=0)check(group->addDSP(argc>8?atoi(argv[8]):1,eq));}else check(channel->addDSP(channelTarget&&argc>8?atoi(argv[8]):0,eq));FMOD_DSP_DESCRIPTION desc{};desc.pluginsdkversion=FMOD_PLUGIN_SDK_VERSION;strcpy(desc.name,"Capture");desc.numinputbuffers=1;desc.numoutputbuffers=1;desc.read=capture;FMOD::DSP* tap;check(s->createDSP(&desc,&tap));if(group)check(group->addDSP(0,tap));else check(channel->addDSP(0,tap));check(channel->setPaused(false));while(frames<8192)check(s->update());check(s->release());fclose(dest);printf("captured %u frames\n",frames);}
